site_name: datamule
theme:
  name: material
nav:
  - Home: index.md
  - Data Providers: providers.md
  - datamule-python:
      - Overview: datamule-python/index.md
      - Examples: 
          - Quickstart: datamule-python/examples/quickstart.md
          - Tesla Risk Factor Language Score: datamule-python/examples/tesla_risk_factor_language_score.md
      - Setting a Data Provider: datamule-python/data_provider.md
      - Package Data: datamule-python/package_data.md
      - Datasets: datamule-python/datasets.md
      - SEC Terminology:
          - Submission Types: datamule-python/sec/submission_types.md
      - Portfolio:
          - Portfolio: datamule-python/portfolio/portfolio.md
          - Submission: datamule-python/portfolio/submission.md
          - Document: datamule-python/portfolio/document.md
          - Tables: 
              - Tables: datamule-python/portfolio/tables/tables.md
              - Table Types: datamule-python/portfolio/tables/types.md
      - Sheet: datamule-python/sheet/sheet.md
      - Index: datamule-python/index/index.md
      - Book: datamule-python/book/book.md
      - Config: datamule-python/config/config.md
      - Filings Constructor: datamule-python/filings_constructor/filings_constructor.md
      - Utils: 
          - 'CIK Filtering': datamule-python/utils/_process_cik_and_metadata_filters.md
          - 'Convenient Functions': 'datamule-python/utils/convenience.md' 

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight
  - def_list
  - admonition
  - pymdownx.details